name: "Test v0 Strategy"
token:
  - "WETH"
  - "VIRTUAL"
  - "AIXBT" 
metric_rules:
  - metric: "price"
    threshold_percentage: 20.0
    measurement_window: "1d"
  - metric: "price"
    threshold_percentage: -20.0
    measurement_window: "1d"


# Alternative strategy definition
#   - name: "Test v0 Strategy"
#     metric_rules:
#       - metric: "price"
#         threshold_percentage: 20.0
#         measurement_window: "1d"
#         token: "WETH"
#       - metric: "price"
#         threshold_percentage: 20.0
#         measurement_window: "1d"
#         token: "VIRTUAL"
#       - metric: "price"
#         threshold_percentage: 20.0
#         measurement_window: "1d"
#         token: "AIXBT"
#       - metric: "price"
#         threshold_percentage: -20.0
#         measurement_window: "1d"
#         token: "WETH"
#       - metric: "price"
#         threshold_percentage: -20.0
#         measurement_window: "1d"
#         token: "VIRTUAL"
#       - metric: "price"
#         threshold_percentage: -20.0
#         measurement_window: "1d"
#         token: "AIXBT"
